"""remove phoneNumber

Revision ID: 414d9e628776
Revises: 88359e0ff5a1
Create Date: 2026-06-23 11:59:37.437194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414d9e628776'
down_revision = '88359e0ff5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_phoneNumber_key'), type_='unique')
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('users_phoneNumber_key'), ['phoneNumber'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
