"""add phone number and otp token

Revision ID: 88359e0ff5a1
Revises: 
Create Date: 2026-06-22 13:05:27.554556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88359e0ff5a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(
    'uq_users_phoneNumber',
    ['phoneNumber']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(
    'uq_users_phoneNumber',
    type_='unique'
)
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
