"""update

Revision ID: 9f4491d1cf09
Revises: 9d1063f1bfed
Create Date: 2026-06-24 20:54:19.053440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4491d1cf09'
down_revision = '9d1063f1bfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meterrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meterrequest', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
