"""update

Revision ID: bf9ef18048ca
Revises: 9f4491d1cf09
Create Date: 2026-06-25 19:13:05.777342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9ef18048ca'
down_revision = '9f4491d1cf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meterrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meterrequest', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
